import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { approveRecommendation, getCustomer, isDemoMode, startCall } from '../lib/api';
import { idempotencyKey, money, prettyMonth } from '../lib/format';
import { useRefresh } from '../context/RefreshContext';
import { useLanguage } from '../i18n/LanguageContext';
import type { CustomerDetail as Detail } from '../types';
import { Icon } from '../components/Icon';
import { Avatar, Badge, ErrorState, Loading } from '../components/UI';

export function CustomerDetail(){
  const {customerId}=useParams();const navigate=useNavigate();const {revision,refresh}=useRefresh();const {t,language,dateLocale}=useLanguage();
  const [detail,setDetail]=useState<Detail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState('');
  const startRequestId=useRef(idempotencyKey());const inFlight=useRef(false);
  useEffect(()=>{let active=true;setLoading(true);getCustomer(Number(customerId)).then(d=>{if(active){setDetail(d);setError('');}}).catch(e=>{if(active)setError((e as Error).message);}).finally(()=>{if(active)setLoading(false);});return ()=>{active=false;};},[customerId,revision]);
  if(loading)return <Loading/>;
  if(error||!detail)return <ErrorState message={error||'Customer not found'} onRetry={()=>navigate('/recommendations')}/>;
  const {customer,current_package:current,proposed_package:offer,usage,recommendation:rec,latest_call:call}=detail;
  if(!rec||!offer)return <div className="page-body"><Link to="/recommendations" className="back-link">{t('Back to recommendations')}</Link><h1>{customer.name}</h1><p>{detail.recommendation_diagnostic?.message||'No eligible recommendation is available for this customer.'}</p></div>;
  const maxGb=Math.max(...usage.map(u=>u.data_gb),current.data_gb,offer.data_gb);
  const count=usage.filter(u=>u.data_gb>current.data_gb||u.call_minutes>current.call_minutes).length;
  const reason=language==='en'?rec.reason:t('Historic fit explanation',{count,offer:offer.name,gb:Math.max(...usage.map(u=>u.data_gb)),minutes:Math.max(...usage.map(u=>u.call_minutes)),oldBill:money(rec.average_bill_minor),newBill:money(offer.monthly_price_minor)});
  const scoreRows=[{label:'Savings value',value:rec.score_breakdown.savings,max:45},{label:'Recurring mismatch',value:rec.score_breakdown.recurrence,max:30},{label:'Usage-to-plan fit',value:rec.score_breakdown.fit,max:25}];
  async function approve(){if(inFlight.current)return;inFlight.current=true;setBusy(true);setActionError('');try{await approveRecommendation(rec!.id);refresh();}catch(e){setActionError((e as Error).message);}finally{inFlight.current=false;setBusy(false);}}
  async function start(){if(inFlight.current)return;inFlight.current=true;setBusy(true);setActionError('');try{const c=await startCall(rec!.id,startRequestId.current);refresh();navigate(`/calls/${c.call_id}`);}catch(e){setActionError((e as Error).message);const next=await getCustomer(Number(customerId)).catch(()=>null);if(next)setDetail(next);}finally{inFlight.current=false;setBusy(false);}}
  return <div className="page-body">
    <Link to="/recommendations" className="back-link"><Icon name="arrow-left" size={17}/>{t('Back to recommendations')}</Link>
    <div className="customer-title-row"><div className="customer-head"><Avatar name={customer.name} seed={customer.id} size="lg"/><div><div className="customer-name-line"><h1>{customer.name}</h1><Badge status={rec.status}/></div><p className="page-subtitle">{t('Customer #{id}',{id:String(customer.id).padStart(4,'0')})} {customer.segment&&t('{segment} subscriber',{segment:t(customer.segment)})} {customer.email&&<><span className="dot-separator">·</span> {customer.email}</>}</p></div></div><div className="customer-actions">{call?<Link className="btn btn-primary" to={`/calls/${call.id}`}><Icon name="history" size={16}/>{t('View conversation')} <Icon name="arrow-right" size={16}/></Link>:rec.status==='pending'?<button disabled={busy||!customer.contact_allowed||customer.do_not_contact} onClick={approve} className="btn btn-primary"><Icon name="check" size={16}/>{t(busy?'Approving…':'Approve contact')}</button>:<button disabled={busy} onClick={start} className="btn btn-primary"><Icon name="phone" size={16}/>{t(busy?'Starting…':'Start demo call')} <Icon name="arrow-right" size={16}/></button>}</div></div>
    {actionError&&<div className="inline-error"><Icon name="alert-circle" size={18}/>{actionError}</div>}
    {isDemoMode&&<div className="notice"><Icon name="info" size={17}/>{t('Customer history is synthetic. The call will be a browser simulation, not a real phone call.')}</div>}
    <div className="detail-top-grid">
      <section className="surface-panel recommendation-card"><p className="eyebrow">{t('RECOMMENDED ACTION')}</p><div className="offer-title"><div><span>{t('Suggested package')}</span><h2>{offer.name}</h2></div><div className="offer-score"><strong>{rec.score}</strong><small>/ 100</small><span>{t('Rule-based match')}</span></div></div><div className="compare-row"><div><span>{t('Current average bill')}</span><strong>{money(rec.average_bill_minor)}</strong><small>{t('Last 3 months')}</small></div><Icon name="arrow-right" size={22}/><div><span>{t('Proposed plan price')}</span><strong>{money(offer.monthly_price_minor)}</strong><small>{t('Per month')}</small></div></div><div className="saving-highlight"><div className="saving-icon"><Icon name="arrow-up-right" size={21}/></div><div><span>{t('Potential monthly savings')}</span><strong>{money(rec.estimated_savings_minor)}</strong><small>{t('Historical estimate, not guaranteed')}</small></div></div></section>
      <section className="surface-panel reasoning-card"><p className="eyebrow">{t('WHY THIS CUSTOMER?')}</p><h2>{t('Transparent reasoning')}</h2><p className="reason-paragraph">{reason}</p><div className="score-breakdown">{scoreRows.map(r=><div className="breakdown-line" key={r.label}><div className="breakdown-label"><span>{t(r.label)}</span><strong>{Number(r.value.toFixed(1))} <small>/ {r.max}</small></strong></div><div className="breakdown-track"><span style={{width:`${r.value/r.max*100}%`}}/></div></div>)}</div><div className="reason-note"><Icon name="shield" size={15}/>{t('This score is not an acceptance probability.')}</div></section>
    </div>
    <div className="detail-bottom-grid">
      <section className="surface-panel usage-panel"><div className="section-heading"><div><p className="eyebrow">{t('HISTORICAL EVIDENCE')}</p><h2>{t('Usage over the last 3 months')}</h2></div><span className="small-tag">{t('Completed months')}</span></div><div className="usage-chart">{usage.map(u=><div key={u.month} className="usage-chart-row"><span className="chart-month">{prettyMonth(u.month,dateLocale)}</span><div className="usage-chart-track"><div className="usage-chart-current" style={{width:`${current.data_gb/maxGb*100}%`}}/><div className="usage-chart-fill" style={{width:`${u.data_gb/maxGb*100}%`}}/></div><span className="chart-value">{u.data_gb} GB</span></div>)}</div><div className="usage-legend"><span><i className="legend-usage"/> {t('Data used')}</span><span><i className="legend-allowance"/> {t('Current plan allowance')}</span></div><div className="table-wrap"><table className="data-table usage-table"><thead><tr><th>{t('Month')}</th><th>{t('Data usage')}</th><th>{t('Minutes')}</th><th>{t('Extra charges')}</th></tr></thead><tbody>{usage.map(u=><tr key={u.month}><td>{prettyMonth(u.month,dateLocale)}</td><td>{u.data_gb} GB</td><td>{u.call_minutes} {t('min')}</td><td>{money(u.extra_charges_minor)}</td></tr>)}</tbody></table></div></section>
      <section className="surface-panel plan-panel"><p className="eyebrow">{t('PACKAGE COMPARISON')}</p><h2>{t('What changes?')}</h2><table className="plan-compare"><thead><tr><th/><th>{t('Current')}</th><th>{t('Proposed')}</th></tr></thead><tbody><tr><td>{t('Package')}</td><td>{current.name}</td><td className="proposed-cell">{offer.name}</td></tr><tr><td>{t('Monthly price')}</td><td>{money(current.monthly_price_minor)}</td><td className="proposed-cell">{money(offer.monthly_price_minor)}</td></tr><tr><td>{t('Data')}</td><td>{current.data_gb} GB</td><td className="proposed-cell">{offer.data_gb} GB</td></tr><tr><td>{t('Calls')}</td><td>{current.call_minutes} {t('min')}</td><td className="proposed-cell">{offer.call_minutes} {t('min')}</td></tr><tr><td>{t('Contract')}</td><td>{current.verified_faq?.contract||t('No minimum')}</td><td className="proposed-cell">{offer.verified_faq?.contract||t('No minimum')}</td></tr></tbody></table><div className="package-note"><Icon name="info" size={17}/><p>{offer.verified_faq?`${offer.verified_faq.roaming} ${offer.verified_faq.rollover} ${offer.verified_faq.activation}`:t('Fictional plans. Extra data: 1 AZN/GB; extra calls: 0.05 AZN/min. No rollover or roaming. Employee processing is required for activation.')}</p></div></section>
    </div>
    {rec.status==='pending'&&!call&&<div className="approval-band"><Icon name="shield" size={23}/><div><strong>{t('Employee approval required')}</strong><p>{t('Review the customer’s usage and package comparison before authorizing a call.')}</p></div><button onClick={approve} className="btn btn-primary" disabled={busy}><Icon name="check" size={16}/>{t('Approve contact')}</button></div>}
  </div>;
}
